### ISSUE TITLE
Make Headful Puppet compatible with proxies

### ISSUE THREAD

**Issue by jpgklassen** [bitmeal/headful-puppet#2]
Before installing Headful Puppet, I was using Puppeteer like this:

```javascript
const puppeteer = require('puppeteer-extra')
const stealth = require('puppeteer-extra-plugin-stealth')()
puppeteer.use(stealth)

let proxies = [
  '123.456.789.0',
  '234.567.890.1',
  '345.678.901.2'
]

let pages = []
for (let i=0; i<proxies.length; i++) {
  let browser = await puppeteer.launch({
    headless: false,
    args: [ '--proxy-server=http://' + proxies[i] + ':3128']
  })
  pages.push(await browser.newPage())
}

let proxyCounter = 0
for (let url of urls) {
  await pages[proxyCounter].goto(url)
  if (proxyCounter < proxies.length-1) {
    proxyCounter++
  } else {
    proxyCounter = 0
  }
}
```

Headful Puppet allows me to do this on a computer with no screen, but I can no longer use my proxies. Can Headful Puppet be updated to allow using proxies?

**Comment by bitmeal** [comment]
Not in the way as you show above; launching a new chromium instance for each proxy server. Chromium does support dynamically changing the used proxy server though.

I have not tried it, but it seems to me there are at least 3 options:
* create a new context (incognito only) and set [`proxyServer` on `BrowserContextOptions`](https://pptr.dev/api/puppeteer.browsercontextoptions) when calling [`createIncognitoBrowserContext`](https://pptr.dev/api/puppeteer.browser.createincognitobrowsercontext)
* [puppeteer-page-proxy](https://github.com/Cuadrix/puppeteer-page-proxy)
* [puppeteer-proxy](https://github.com/gajus/puppeteer-proxy)

**Comment by jpgklassen** [comment]
Hey @bitmeal, I tried the first option and it worked! Thanks so much!
